export const books = [
{title:'I never knew it was you',price:'35$',img:require('../style/img/book1.png'),tags:'Science',SpcOffers:false},
{title:'The Hare With Amber Eyes',price:'66$',img:require('../style/img/book2.png'),tags:'Fantasy',SpcOffers:true},
{title:'The war of art',price:'78$',img:require('../style/img/book3.png'),tags:'History',SpcOffers:false},
{title:'Can love Happen Jwice?',price:'55$',img:require('../style/img/book4.png'),tags:'Romance',SpcOffers:true},
{title:'MELUHA',price:'44$',img:require('../style/img/book5.png'),tags:'Horror',SpcOffers:false},
{title:'Life what you make it',price:'60$',img:require('../style/img/book6.png'),tags:'Romance',SpcOffers:true},
{title:'BABA',price:'69$',img:require('../style/img/book7.png'),tags:'Mystery',SpcOffers:false},
{title:'The long dark',price:'99$',img:require('../style/img/book8.png'),tags:'Crime',SpcOffers:false},
{title:'The ARAMGEDON RAG',price:'81$',img:require('../style/img/book9.png'),tags:'Fantasy',SpcOffers:false},
{title:'A Walk Across the Sun',price:'16$',img:require('../style/img/book10.png'),tags:'Romance',SpcOffers:false},
{title:'Jeffrey archer the sins od the father',price:'48$',img:require('../style/img/book11.png'),tags:'Poetry',SpcOffers:false},
{title:'Roads',price:'55$',img:require('../style/img/book12.png'),tags:'Literature',SpcOffers:false},
{title:'The war of art',price:'43$',img:require('../style/img/book13.png'),tags:'Crime',SpcOffers:false},
{title:'MELUHA',price:'35$',img:require('../style/img/book5.png'),tags:'Horror',SpcOffers:false},
{title:'The Hare With Amber Eyes',price:'30$',img:require('../style/img/book2.png'),tags:'Fantasy',SpcOffers:true},
{title:'Life what you make it',price:'75$',img:require('../style/img/book6.png'),tags:'Art',SpcOffers:false},
{title:'LOVE',price:'77$',img:require('../style/img/book4.png'),tags:'Art',SpcOffers:false},
{title:'WAR',price:'84$',img:require('../style/img/book3.png'),tags:'Crime',SpcOffers:false},
{title:'LOVE',price:'110$',img:require('../style/img/book4.png'),tags:'Fantasy',SpcOffers:true},
{title:'Name your Book',price:'32$',img:require('../style/img/book5.png'),tags:'Fantasy',SpcOffers:false},
{title:'Life what you make it',price:'39$',img:require('../style/img/book6.png'),tags:'Comic',SpcOffers:false},
{title:'BABA',price:'99$',img:require('../style/img/book7.png'),tags:'Cook',SpcOffers:false},
{title:'The long dark',price:'48$',img:require('../style/img/book8.png'),tags:'Mystery',SpcOffers:false},
{title:'World',price:'49$',img:require('../style/img/book8.png'),tags:'History',SpcOffers:false},
{title:'Some big book',price:'45$',img:require('../style/img/book8.png'),tags:'History',SpcOffers:false},
{title:'Html/CSS',price:'37$',img:require('../style/img/book1.png'),tags:'Computer',SpcOffers:false},
{title:'Space',price:'33$',img:require('../style/img/book4.png'),tags:'Fantasy',SpcOffers:false},
{title:'War in space',price:'20$',img:require('../style/img/book14.png'),tags:'Fantasy',SpcOffers:false},
{title:'COD',price:'90$',img:require('../style/img/book1.png'),tags:'Law',SpcOffers:false},
{title:'Beautiful code',price:'80$',img:require('../style/img/book4.png'),tags:'Computer',SpcOffers:false},
{title:'The ARAMGEDON RAG',price:'70$',img:require('../style/img/book2.png'),tags:'Travel',SpcOffers:false},
{title:'Life what you make it',price:'60$',img:require('../style/img/book4.png'),tags:'Psychology',SpcOffers:false},
{title:'I never knew it was you',price:'77$',img:require('../style/img/book9.png'),tags:'Psychology',SpcOffers:false},
{title:'Name your Book',price:'60$',img:require('../style/img/book8.png'),tags:'Psychology',SpcOffers:false},
{title:'I never knew it was you',price:'35$',img:require('../style/img/book1.png'),tags:'Psychology',SpcOffers:true},
{title:'The Hare With Amber Eyes',price:'66$',img:require('../style/img/book2.png'),tags:'Budiness',SpcOffers:false},
{title:'The war of art',price:'78$',img:require('../style/img/book3.png'),tags:'Photography',SpcOffers:false},
{title:'Can love Happen Jwice?',price:'55$',img:require('../style/img/book4.png'),tags:'Baby',SpcOffers:false},
{title:'MELUHA',price:'44$',img:require('../style/img/book5.png'),tags:'Travel',SpcOffers:false},
{title:'Life what you make it',price:'60$',img:require('../style/img/book6.png'),tags:'Science',SpcOffers:true},
{title:'BABA',price:'69$',img:require('../style/img/book7.png'),tags:'Sports',SpcOffers:false},
{title:'The long dark',price:'99$',img:require('../style/img/book8.png'),tags:'Sports',SpcOffers:false},
{title:'The ARAMGEDON RAG',price:'81$',img:require('../style/img/book9.png'),tags:'Sports',SpcOffers:false},
{title:'A Walk Across the Sun',price:'16$',img:require('../style/img/book10.png'),tags:'Children',SpcOffers:false},
{title:'Jeffrey archer the sins od the father',price:'48$',img:require('../style/img/book11.png'),tags:'Children',SpcOffers:false},
{title:'Roads',price:'55$',img:require('../style/img/book12.png'),tags:'Children',SpcOffers:false},
{title:'The war of art',price:'43$',img:require('../style/img/book13.png'),tags:'Poetry',SpcOffers:false},
{title:'MELUHA',price:'35$',img:require('../style/img/book5.png'),tags:'Children',SpcOffers:false},
{title:'The Hare With Amber Eyes',price:'30$',img:require('../style/img/book2.png'),tags:'Children',SpcOffers:false},
{title:'Life what you make it',price:'75$',img:require('../style/img/book6.png'),tags:'Children',SpcOffers:false},
{title:'LOVE',price:'77$',img:require('../style/img/book4.png'),tags:'Children',SpcOffers:false},
{title:'WAR',price:'84$',img:require('../style/img/book3.png'),tags:'Literature',SpcOffers:false},
{title:'LOVE',price:'110$',img:require('../style/img/book4.png'),tags:'Literature',SpcOffers:false},
{title:'Name your Book',price:'32$',img:require('../style/img/book5.png'),tags:'Literature',SpcOffers:true},
{title:'Life what you make it',price:'39$',img:require('../style/img/book6.png'),tags:'Cook',SpcOffers:false},
{title:'BABA',price:'99$',img:require('../style/img/book7.png'),tags:'Cook',SpcOffers:false},
{title:'The long dark',price:'48$',img:require('../style/img/book8.png'),tags:'Cook',SpcOffers:false},
{title:'World',price:'49$',img:require('../style/img/book8.png'),tags:'Cook',SpcOffers:false},
{title:'Some big book',price:'45$',img:require('../style/img/book8.png'),tags:'Comic',SpcOffers:true},
{title:'Hello guys',price:'37$',img:require('../style/img/book1.png'),tags:'Comic',SpcOffers:true},
{title:'Space',price:'33$',img:require('../style/img/book4.png'),tags:'Comic',SpcOffers:false},
{title:'Surgeon',price:'20$',img:require('../style/img/book5.png'),tags:'Medical',SpcOffers:false},
{title:'Your Body',price:'90$',img:require('../style/img/book1.png'),tags:'Medical',SpcOffers:false},
{title:'Medicine',price:'80$',img:require('../style/img/book4.png'),tags:'Medical',SpcOffers:false},
{title:'The ARAMGEDON RAG',price:'70$',img:require('../style/img/book2.png'),tags:'Education',SpcOffers:false},
{title:'Life what you make it',price:'60$',img:require('../style/img/book4.png'),tags:'Education',SpcOffers:false},
{title:'I never knew it was you',price:'77$',img:require('../style/img/book9.png'),tags:'Education',SpcOffers:true},
{title:'World',price:'49$',img:require('../style/img/book8.png'),tags:'Fiction',SpcOffers:false},
{title:'Some big book',price:'45$',img:require('../style/img/book8.png'),tags:'Fiction',SpcOffers:false},
{title:'Hello guys',price:'37$',img:require('../style/img/book1.png'),tags:'Fiction',SpcOffers:false},
{title:'Space',price:'33$',img:require('../style/img/book4.png'),tags:'Fiction',SpcOffers:false},
{title:'War in space',price:'20$',img:require('../style/img/book5.png'),tags:'Education',SpcOffers:true},
{title:'COD',price:'90$',img:require('../style/img/book1.png'),tags:'Fiction',SpcOffers:false},
{title:'Fiction',price:'80$',img:require('../style/img/book4.png'),tags:'Fiction',SpcOffers:false},
{title:'The ARAMGEDON RAG',price:'70$',img:require('../style/img/book2.png'),tags:'Health',SpcOffers:true},
{title:'Life what you make it',price:'60$',img:require('../style/img/book4.png'),tags:'Health',SpcOffers:false},
{title:'I never knew it was you',price:'77$',img:require('../style/img/book9.png'),tags:'Mathematics',SpcOffers:true},
{title:'JavaScript',price:'80$',img:require('../style/img/book4.png'),tags:'Computer',SpcOffers:false},
{title:'The ARAMGEDON RAG',price:'70$',img:require('../style/img/book2.png'),tags:'Mathematics',SpcOffers:false},
{title:'Life what you make it',price:'60$',img:require('../style/img/book4.png'),tags:'Mathematics',SpcOffers:false},
{title:'I never knew it was you',price:'77$',img:require('../style/img/book9.png'),tags:'Reference',SpcOffers:true},
{title:'MAGIC',price:'133$',img:require('../style/img/book14.png'),tags:'BestSellers',SpcOffers:false},
{title:'Some book',price:'225$',img:require('../style/img/bookSteller.PNG'),tags:'BestSellers',SpcOffers:false},
{title:'Alter EGO',price:'321$',img:require('../style/img/bookSteller2.PNG'),tags:'BestSellers',SpcOffers:false},
]